### ISSUE TITLE
Simulation coefficients equal to 0

### ISSUE THREAD

**Issue by Free-rider** [kaybenleroll/carinsurance_pricing#2]
Hello,

in 3.2 Simulation Using Standard Errors for Parameters there is a function called ` run_mc_sim` and I see that inside the function:

` as.vector(coef(arm::sim(claim_model_05, n.sim = 1)))`

is always 0. When I use n.sim = 1 always all coef are equal to 0. 

Is there something wrong?

**Comment by kaybenleroll** [comment]
It has been a while since I looked at that, so I will have to check and get back to you.

**Comment by kaybenleroll** [comment]
But thanks very much for the feedback - nice to know that someone other than myself is looking at this stuff. :)

**Comment by Free-rider** [comment]
Thanks to you for post this sort of things, I am looking your work and conclusions. I am doing a GLM pricing right now, if I see any improvement I will let you know. 

I've never used the function sim() . I don't understand why using `n.sim = 1` all coefficients are equal to 0. If I use `n.sim = 2` or more, all coef are different to 0. I will wait for your feedback. 

Thanks for your time.

**Comment by kaybenleroll** [comment]
I've finally found time to look at all this stuff, so I'll have more updates here as I go through them.

**Comment by kaybenleroll** [comment]
It looks like this is an issue with `sim()` in the *arm* package when you just run it for a single simulation.

I'm not entirely sure what is going on, but I've put in a workaround when I redo most of the work.
